FROM quay.io/savkov/alpine-pandas
MAINTAINER "Sasho Savkov" <me@sasho.io>

ARG CC_TEST_REPORTER_ID

ENV CC_TEST_REPORTER_ID=$CC_TEST_REPORTER_ID

# copying requirements
COPY requirements.txt /opt/project/
COPY test_requirements.txt /opt/project/

# installing requirements
RUN pip install -r /opt/project/test_requirements.txt

# make sure the testing directory exists
RUN mkdir /data && mkdir /data/.test

# copyting the project
COPY . /opt/project

# copy dummie file for the client test
RUN cp /opt/project/test/data/client_input_file.csv /data/.test/

# set working directory
WORKDIR /opt/project

# set up code climate test reporter
RUN apk add curl git && \
  curl -L -o cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 && \
  chmod +x cc-test-reporter

CMD ["sh", "test-coverage.sh"]
